# Site settings
title: Miguel López Virués
email: miguel.lopezvirues@gmail.com
# url: https://github.com/jeromelachaud/freelancer-theme
description: "Hi! I'm Miguel, it's great to meet you! This a portfolio website that I just recently created to share some of the personal projects I have been working on. With time, you'll be able to find projects about Data Science in general here: Machine Learning, visualization, statistics, web scraping, etc. In case you'd like to offer me a collaboration of a project to work on together, contact me on the form below or feel free to send me an email!"
keywords: "Machine learning, Python, Pandas, Numpy, Scikit-learn, SQL, Azure Machine Learning"
skills: "Data Science - Data Analyst - Python"
meta_author: Lopez Virues Miguel

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2c3e50 
  primary-rgb:  "	80, 62, 44"  
  secondary:  2c3e50
  secondary-dark:  233140
  text1: FCFBFF
  text2: 2c3e50

# Footer settings
footer:
  copyright: Miguel López Virués
  location: Location
  social: Also find me on
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/miguel-lopez-vir/
  - title: github
    url: https://github.com/MiguelLopezVirues

# Postal address (add as many lines as necessary)
address:
  - line: Tomares
  - line: Sevilla, CP 41001

# Credits content
credits: 'This is a portfolio page based on Jekyll and Bootstrap.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
